// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYHLgYIWTw5vKaYhP9oyGOFyVzckqfZx8',
    appId: '1:851881770220:web:2af8ff0c4c7a232b2bb9c9',
    messagingSenderId: '851881770220',
    projectId: 'airplane2-47cd9',
    authDomain: 'airplane2-47cd9.firebaseapp.com',
    storageBucket: 'airplane2-47cd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdd7jeVcwzCBazhRhKGaLod9clmttGy8',
    appId: '1:851881770220:android:d29bc2e28db18ab42bb9c9',
    messagingSenderId: '851881770220',
    projectId: 'airplane2-47cd9',
    storageBucket: 'airplane2-47cd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlBKvQa0tPr0Iud0SWt9Uv6A2ilywRiM',
    appId: '1:851881770220:ios:8220188915891a882bb9c9',
    messagingSenderId: '851881770220',
    projectId: 'airplane2-47cd9',
    storageBucket: 'airplane2-47cd9.appspot.com',
    iosClientId: '851881770220-ak9pr7f1lufpeoscbcjoun3jipthllvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqlBKvQa0tPr0Iud0SWt9Uv6A2ilywRiM',
    appId: '1:851881770220:ios:8220188915891a882bb9c9',
    messagingSenderId: '851881770220',
    projectId: 'airplane2-47cd9',
    storageBucket: 'airplane2-47cd9.appspot.com',
    iosClientId: '851881770220-ak9pr7f1lufpeoscbcjoun3jipthllvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplane',
  );
}
